### PR TITLE
ci: add GitHub Actions

### PR DESCRIPTION
**Pull request by Zxilly**
Signed-off-by: Zxilly <zhouxinyu1001@gmail.com>

### CODE REVIEW

**Comment by Zxilly** [comment]
@hsluoyz @nodece plz review

**Comment by nodece** [comment]
@Zxilly I think you should add file adapter in node-casbin project, This is my current idea:https://github.com/casbin/node-casbin/issues/257#issuecomment-829001237

**Comment by Zxilly** [comment]
@nodece Do you mean git submodule?

**Comment by nodece** [comment]
@Zxilly no, I want to add fs/memeory-adapter and fs/memory-model to node-casbin project, no need to split repository.

**Comment by Zxilly** [comment]
@nodece So we just need move `fileAdapter.ts` to fs folder and split `model.ts`?

**Comment by nodece** [comment]
@Zxilly we just need to use momery-model/apdater instead of fs-model/adapter as default, node-casbin only uses string/memory adapter/model for cross-platform compatible. 

you can checkout: 
https://github.com/casbin/node-casbin/issues/257#issuecomment-828745874
https://github.com/casbin/node-casbin/issues/257#issuecomment-828720926

**Pull request closed without merging**
